README.md
test/features/sampleSnippets.feature
test/support/init.js

Adding the possibility to isolate single or multiple scenarios

Adding @isolate tag

---

test/features/githubSearch.feature

**This pull request updates login test description**

Updated login test description

---

package.json
test/steps/given.js
test/support/helper/checkContent.js
test/support/helper/checkCookieContent.js
test/support/helper/checkCookieExists.js
test/support/helper/checkDimension.js
test/support/helper/checkElementExists.js
test/support/helper/checkOffset.js
test/support/helper/checkProperty.js
test/support/helper/checkSelected.js
test/support/helper/checkTitle.js
test/support/helper/compareText.js
test/support/helper/isExisting.js
test/support/helper/isVisible.js
test/support/helper/login.js
test/support/helper/waitfor.js

Updated dependencies and ran all the tests

Updated dependencies in package.json

---

.travis.yml
README.md
package.json

Separate commands to improve Windows compatibility

---

README.md
demo-app/inc/script.js
demo-app/index.html
test/features/moveTo.feature
test/steps/when.js
test/support/action/moveToElement.js

Added a when-rule corresponding with the moveToElement method in webdriverio

Feature/moveToElement rule 

---

test/features/elementPosition.feature
test/features/githubSearch.feature
test/features/login.feature
test/features/withinViewport.feature
test/hooks/after.js
test/support/custom/login.js
test/support/pageObjects/githubPage.js

- fixed github feature files for actual github.com so they pass; resized window for login.js when logging in to github;
- fix for after.js to prevent "done invoked with non.error" from happening

actualized 

---

.codeclimate.yml
.travis.yml
CHANGELOG.md
README.md
package.json

- Dependency monitor switched from David to VersionEye
- Updated the readme to change the badges & fix the main heading
- CodeClimate integration & test-coverage

Version 1.1.1

---

jest.json

Fixes #79
Just a quick config syntax swap out. Unsure about backwards compatibility implications.
- [-] Added rules are described in the [readme file](README.md)

use new syntax for jest.json

---

.travis.yml
src/features/select.feature
src/support/action/selectOption.js
test/support/action/selectOption.spec.js

Add missing tests to select.feature
Fix selectOption action

fix #140 add missing tests to select.feature

---

.eslintrc.yaml
CHANGELOG.md
jest.json
package.json
yarn.lock

Release 1.3.1

---

README.md
src/steps/then.js

Checks that the element is on the page a specific number of times

check element exists n amount of times

---

CHANGELOG.md
README.md
package.json
yarn.lock

Added correct Node & Yarn versions to tehe readme

Updated changelog & version

---

demo-app/index.html
src/features/attribute.feature
src/support/check/checkProperty.js

Fixed checking font-weight returned an object, fixes #144

---

README.md

The selector for the search input at google.com has changed

Update selector for Google search input

---

README.md

There are some points that need to be improved in the documentation. I fixed them all in this PR.

Added some English language improvements in the documentation.

---

src/support/check/checkDimension.js

Corrected a typo in variable name "originalSize"
originalSize variable name corrected

Corrected a typo

---

src/support/check/checkFontProperty.js

Duplicate comparison attributes removed

Duplicates removed

---

src/steps/then.js
src/support/check/checkTitleContains.js

Added checkTitleContains() to help in matching partial titles as well

Added check title contains

---

src/support/check/checkProperty.js

Attribute name added to corrected assertion log

Attribute name added to corrected assertion log

---

src/support/check/checkModalText.js

Corrected assertion log

---

src/support/check/checkFontProperty.js

Assertion message corrected and added attribute type to log

Assertion and log corrected

---

README.md

> Updates Gherkin link in README

#342: Update Gherkin doc link

---

.github/CONTRIBUTING.md
README.md
package.json
src/features/githubSearch.feature

> Update outdate documentation

Issue [418] update outdated documentation

---

package-lock.json
package.json
src/steps/given.ts
src/steps/then.ts
src/steps/when.ts
src/support/action/closeAllButFirstTab.ts
src/support/action/closeLastOpenedWindow.ts
src/support/action/focusLastOpenedWindow.ts
src/support/action/waitForDisplayed.ts
src/support/check/checkContainsAnyText.ts
src/support/check/checkIsOpenedInNewWindow.ts
wdio.BUILD.conf.ts

update ts, eslint, chromedriver; fix lint errors
